### ISSUE TITLE
flashvars option details

### ISSUE THREAD

**Issue by pkvince** [pauln/local-audio-recorder#1]
I would like to know which options can be passed to the flash plugin using flashvars...

It works well but I would like to control how the POST request is done and how to manage the response from the server (a JSON dictionary).

The README says it's possible to handle the POST request ourselves, but I would like to know how exactly...

Thank you for your help on using your great plugin! :)

**Comment by pauln** [comment]
Sorry for the incredibly slow/late response, but I've just added a rundown of the standard flashvars / options to the readme.  If you want to handle the POST request yourself, set the "gateway" parameter to "form" and specify a JavaScript function name in the "callback" parameter - it will be called with two arguments: the filename and the file data.  See the demo for an example of a JS callback; it doesn't do a form submission, though.
