### ISSUE TITLE
upload

### ISSUE THREAD

**Issue by fsdevpoint3** [pauln/local-audio-recorder#4]
I try to write the file oin server side (php) but its impossible for me to get it working. What ever i try on php i get no bytearray. Can you add small example for the upload.php? Please its very important and urgent forme to get this running :(

**Comment by pauln** [comment]
If you're just setting a POST URL (`gateway` parameter), the file will be in PHP's regular `$_FILES` array - see [this page](http://www.php.net/manual/en/features.file-upload.post-method.php) on the PHP website for help on handling the uploaded file.  If you have not specified a field name (`filefield` parameter), the field name will be "newfile" (so you will access it as `$_FILES['newfile']`).

If you're using a JavaScript callback, how you access the data will depend on how you're sending it to the server.

**Comment by fsdevpoint3** [comment]
i try this but no luck :(

<?php

   $fp = fopen("upload/xx.wav", "wb");

   fwrite($fp, $_FILES['newfile']);

   fclose($fp);

   exit('done');

?>

in the created wav file its only text "Array"

**Comment by pauln** [comment]
If you follow the link in my earlier post, you will find that `$_FILES['newfile']` does not contain the raw data - it is an array of information about the uploaded file.  If all you want to do is store the file, you can use something like this:

```
<?php
    move_uploaded_file($_FILES['newfile']['tmp_name'], "upload/xx.wav");
?>
```

That would save it as `upload/xx.wav` - but if you want to store it using the file name provided in the recorder, you can simply use:

```
<?php
    move_uploaded_file($_FILES['newfile']['tmp_name'], "upload/".$_FILES['newfile']['name']);
?>
```

See http://www.php.net/manual/en/function.move-uploaded-file.php for more information on `move_uploaded_file()`.

**Comment by fsdevpoint3** [comment]
thats it! very great any many thanks!

just a question, why the callback not work if i set to "form" and callback as you has on demo? if i try that "uploading, please wait.." stay and nothing more

**Comment by fsdevpoint3** [comment]
your php code with save to filename from recorder give a error: 

Warning: move_uploaded_file(upload/oo .mp3) [function.move-uploaded-file]: failed to open stream: Invalid argument in C:\inetpub\vhosts\xxx\httpdocs\audioRec\upload-works.php on line 2

Warning: move_uploaded_file() [function.move-uploaded-file]: Unable to move 'C:\Windows\Temp\phpB12.tmp' to 'upload/oo .mp3' in C:\inetpub\vhosts\xxx\httpdocs\audioRec\upload-works.php on line 2

**Comment by fsdevpoint3** [comment]
Any news/help here?
