### ISSUE TITLE
no mp3 recording

### ISSUE THREAD

**Issue by ukpatel890** [pauln/local-audio-recorder#5]
it shows recording can be done in mp3 or wav format, but how to change recording format to mp3 ?

**Comment by pauln** [comment]
As per the "Options" section of the readme:
- `format`: Output format.  Set to "wav" to have local-audio-recorder produce a WAV file; otherwise it will default to MP3.

**Comment by ukpatel890** [comment]
yes done, sorry, i didn't noticed it in code
