### ISSUE TITLE
.fla file to make change in look and feel of swf file

### ISSUE THREAD

**Issue by ukpatel890** [pauln/local-audio-recorder#6]
Your recorder is working perfectly with good sound recording quality, but i need to make change in look of recorder, for that i need fla file, can you provide me fla file ?

**Comment by pauln** [comment]
Source files are in the `src` directory.

**Comment by ukpatel890** [comment]
that fla file in src directory is damaged or not working properly,check screen shot i have attached
![swf-file](https://cloud.githubusercontent.com/assets/12195168/7514337/2695d536-f4da-11e4-9002-6ddb97e9efa9.jpg)
